extends Node

enum TRIGGER_TYPE{CHANGE_TRACK, BREAK_ZONE}

enum RED_LIGHT_MODE{NORMAL, WARNING, BROKEN}
enum RED_LIGHT_COLOR{RED, ORANGE, GREEN}

enum DRIVER_MOOD{NORMAL, DRUNK, FAST}

enum GAME_OVER_TYPE{CRUSHED_BY_CAR, FELL_IN_SEEKER}
